# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrainBitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'neurosdk2', '~> 1.0.6.2'

  # Pods for BrainBitDemo

end
